### ISSUE TITLE
Generation fails code in a net47 project that references a netstandard2.0

### ISSUE THREAD

**Issue by jeromelaban** [nventive/Uno.SourceGeneration#2]
The source generation fails code in a net47 project that references a netstandard2.0.

A possible workaround is to include a net47 target framework in the referenced project.

See this roslyn issue: https://github.com/dotnet/roslyn/issues/23114

**Comment by FrancoisM** [comment]
Error when referencing a net standard 2.0 library into iOS:

> Error		System.InvalidOperationException: The project(s) MyApp.Services.Interfaces did not provide any metadata reference. This may be due to an invalid path, such as $(SolutionDir) being used in the csproj; try using relative paths instead.This may also be related to a missing default configuration directive. Refer to the Uno.SourceGenerator Readme.md file for more details.
>    at Uno.SourceGeneration.Host.SourceGeneratorHost.<GetCompilation>d__4.MoveNext() in C:\projects\uno-sourcegeneration\src\Uno.SourceGenerationHost.Shared\SourceGeneratorHost.cs:line 303	MyApp.Uno.iOS	

I tried to directly target iOS into my library but same error.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;Xamarin.iOS10;MonoAndroid71</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MsBuild.Sdk.Extras" Version="1.5.4" PrivateAssets="All" />
    <PackageReference Include="System.Reactive" Version="4.0.0" />
  </ItemGroup>
  
  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />

</Project>
```

**Comment by jeromelaban** [comment]
@FrancoisM could you try using `xamarinios10` instead of `Xamarin.iOS10` ?

**Comment by FrancoisM** [comment]
> The TargetFramework value 'xamarinios10' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	MyApp.Services.Interfaces	C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	96

**Comment by jeromelaban** [comment]
Make sure to delete the obj folder, and try a rebuild. msbuild is quite sensitive with the TF changes

**Comment by FrancoisM** [comment]
It worked.

**Comment by paulovila** [comment]
If the project is using EnumMember the buildsays :
_2>ButchersQA.WebClient.cs(534,147,534,166): error CS1069: The type name 'EnumMemberAttribute' could not be found in the namespace 'System.Runtime.Serialization'. This type has been forwarded to assembly 'System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' Consider adding a reference to that assembly._

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;xamarinios10</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MsBuild.Sdk.Extras" Version="1.5.4" PrivateAssets="All" />
    <PackageReference Include="System.Reactive" Version="4.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>
  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />
</Project>
```
Even if I add the Package reference as
`    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
`
It still says the same error, should I use another package?
