### ISSUE TITLE
How can I write something to Build output pane of visual studio?

### ISSUE THREAD

**Issue by ysmoradi** [nventive/Uno.SourceGeneration#23]
Neither Console/Debug/Trace write line methods are working.

**Comment by jeromelaban** [comment]
There are three ways to do logging: 
- Use the `Debug.WriteLine` while [the debugger is attached](https://github.com/nventive/Uno.SourceGeneration#debugging-a-generator)
- Write as comments a generated file
- Run msbuild in cmd/powerhshell and use `Console.WriteLine`


The [SourceGeneratorContext](https://github.com/nventive/Uno.SourceGeneration/blob/68670fe6a5584170be0ab78689526e69b471c3d7/src/Uno.SourceGeneration/SourceGeneratorExtensions.cs#L31) shoud provide a way to get the main logger, but there are unknown issues on macOS that make the app domain fail.

**Comment by ysmoradi** [comment]
Thanks, @jeromelaban (-:
I'm not interested in mac os at the moment. So could you please show me the hack!

**Comment by jeromelaban** [comment]
[This logger](https://github.com/nventive/Uno.SourceGeneration/blob/68670fe6a5584170be0ab78689526e69b471c3d7/src/Uno.SourceGenerationHost.Shared/Helpers/TaskLogger.cs#L24) should be surfaced through SourceGeneratorContext, so the generators can log to the output. For now, it's linked to an Uno.Core logging context, but it's not very efficient.

**Comment by carldebilly** [comment]
Just created a PR: #30 
Should provide required logging.  I'll add documentation before completing it.

**Comment by carldebilly** [comment]
PR completed.  @ysmoradi please check if you're happy with this solution.

**Comment by ysmoradi** [comment]
It's working like a charm man (-: Thanks so much.

**Comment by carldebilly** [comment]
You're welcome.
