### ISSUE TITLE
context.Project.Solution.FilePath is null

### ISSUE THREAD

**Issue by ysmoradi** [nventive/Uno.SourceGeneration#24]
I guess it's not directly related to Uno.SourceGeneration.
Do you have any idea how to get solution's path?
Thanks in advance.

**Comment by ysmoradi** [comment]
I have a project called bit framework, and it has a code generator which generates some javascript/typescript codes (and soon some C# codes) for C#/JS clients based on server side C# codes.
Code generator uses the power of Roslyn and visual studio workspace in VSIX package.
Everything is fine, except for two things. Solution file path and logging. With hardcoded solution file path, my code generator is working fine.

**Comment by ysmoradi** [comment]
Sorry, I wasn't able to understand what should I write in term of C# codes. I was unable to find solution path )-:

**Comment by jeromelaban** [comment]
You won't have any other choice than hard-coding the solution path somewhere. The best place for that is Directory.props, but I suggest you avoid using the solution information during the source generation.

**Comment by ysmoradi** [comment]
@carldebilly Do you've any idea about this? This is my last issue about code generation using Uno.SourceGeneration
I managed to find a workaround, but I need something cool.
Thanks in advance.
