### ISSUE TITLE
Reason behind choosing net 462

### ISSUE THREAD

**Issue by ysmoradi** [nventive/Uno.SourceGeneration#70]
The uno.sourcegeneration.1.29.0-dev.161 is using net46 & uno.sourcegeneration.1.29.0-dev.178 is using net 462 )-:
If you need .net standard 2.0 support, then you can use net461
Could you please do something for this too?
Thanks in advance.

**Comment by ysmoradi** [comment]
.net 461 is being installed by default within the visual studio. Most of our customers are using that. It would be nice if we can use net 461

**Comment by jeromelaban** [comment]
Should be all good now :)
